package tamagotchi;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author eric
 */
public class VueGameTamagotchi extends javax.swing.JFrame {

    static Tama monTama;
    private JFrame frame;
    CustomDialog pane = new CustomDialog(frame, rootPaneCheckingEnabled, "Confirmer ?");
    
    /**
     * Creates new form VueTamagotchi
     */
    public VueGameTamagotchi() {
        
        initComponents();
        char sex = VueHomeTamagotchi.sex.charAt(0);
        monTama = new Tama(VueHomeTamagotchi.name, sex);
        nameNewjTextField1.setText(monTama.getNom());
        sexNewjTextField2.setText(monTama.getSexe()+"");
        actualiserStatus();
        VueGifjLabel.setIcon(imageAdd("kreeper", "gif"));
        
    }

    private void showDialog() {
        pane.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainGameJPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        hygieneJProgressBar = new javax.swing.JProgressBar();
        suicidejButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        besoinJProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        poidsJProgressBar2 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        sexNewjTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        faimJProgressBar3 = new javax.swing.JProgressBar();
        santeJProgressBar4 = new javax.swing.JProgressBar();
        humeurJProgressBar5 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameNewjTextField1 = new javax.swing.JTextField();
        testStartjButton1 = new javax.swing.JButton();
        VueGifjLabel = new javax.swing.JLabel();
        backButtonjPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        goEatjButton = new javax.swing.JButton();
        goPoopjButton = new javax.swing.JButton();
        goSportjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutDialjTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        goSleepjButton = new javax.swing.JButton();
        goShowerjButton = new javax.swing.JButton();
        goGamejButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setPreferredSize(new java.awt.Dimension(625, 454));

        mainGameJPanel.setMaximumSize(new java.awt.Dimension(625, 460));

        jPanel5.setMaximumSize(new java.awt.Dimension(1920, 1080));

        hygieneJProgressBar.setBackground(new java.awt.Color(255, 0, 0));
        hygieneJProgressBar.setForeground(new java.awt.Color(51, 255, 102));

        suicidejButton.setText("KILL");
        suicidejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suicidejButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Poids");

        besoinJProgressBar1.setBackground(new java.awt.Color(255, 0, 0));
        besoinJProgressBar1.setForeground(new java.awt.Color(51, 255, 102));

        jLabel5.setText("Hygiene");

        poidsJProgressBar2.setBackground(new java.awt.Color(255, 0, 0));
        poidsJProgressBar2.setForeground(new java.awt.Color(51, 255, 102));

        jLabel6.setText("Besoin");

        sexNewjTextField2.setEditable(false);
        sexNewjTextField2.setFocusable(false);
        sexNewjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexNewjTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(besoinJProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hygieneJProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poidsJProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(suicidejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sexNewjTextField2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sexNewjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poidsJProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hygieneJProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(besoinJProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(suicidejButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        faimJProgressBar3.setBackground(new java.awt.Color(255, 0, 0));
        faimJProgressBar3.setForeground(new java.awt.Color(51, 255, 102));

        santeJProgressBar4.setBackground(new java.awt.Color(255, 0, 0));
        santeJProgressBar4.setForeground(new java.awt.Color(51, 255, 102));
        santeJProgressBar4.setFocusable(false);

        humeurJProgressBar5.setBackground(new java.awt.Color(255, 0, 0));
        humeurJProgressBar5.setForeground(new java.awt.Color(51, 255, 102));

        jLabel1.setText("Santé");

        jLabel2.setText("Faim");

        jLabel3.setText("Humeur");

        nameNewjTextField1.setEditable(false);
        nameNewjTextField1.setFocusable(false);
        nameNewjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameNewjTextField1ActionPerformed(evt);
            }
        });

        testStartjButton1.setText("Start");
        testStartjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testStartjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameNewjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(santeJProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faimJProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(humeurJProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(testStartjButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameNewjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(santeJProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faimJProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(humeurJProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(testStartjButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VueGifjLabel.setBackground(new java.awt.Color(0, 153, 51));
        VueGifjLabel.setForeground(new java.awt.Color(0, 187, 187));
        VueGifjLabel.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(VueGifjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VueGifjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        backButtonjPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));

        goEatjButton.setText("Manger");
        goEatjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goEatjButtonActionPerformed(evt);
            }
        });

        goPoopjButton.setText("Toilettes");
        goPoopjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goPoopjButtonActionPerformed(evt);
            }
        });

        goSportjButton.setText("Sport");
        goSportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goSportjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(goPoopjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(goEatjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(goSportjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goEatjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goPoopjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goSportjButton)
                .addGap(23, 23, 23))
        );

        OutDialjTextArea.setEditable(false);
        OutDialjTextArea.setColumns(20);
        OutDialjTextArea.setRows(5);
        OutDialjTextArea.setFocusable(false);
        jScrollPane1.setViewportView(OutDialjTextArea);

        goSleepjButton.setText("Dormir");
        goSleepjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goSleepjButtonActionPerformed(evt);
            }
        });

        goShowerjButton.setText("Douche");
        goShowerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goShowerjButtonActionPerformed(evt);
            }
        });

        goGamejButton.setText("Jouer");
        goGamejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goGamejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(goGamejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(goShowerjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
            .addComponent(goSleepjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goSleepjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goShowerjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goGamejButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backButtonjPanelLayout = new javax.swing.GroupLayout(backButtonjPanel);
        backButtonjPanel.setLayout(backButtonjPanelLayout);
        backButtonjPanelLayout.setHorizontalGroup(
            backButtonjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonjPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backButtonjPanelLayout.setVerticalGroup(
            backButtonjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backButtonjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainGameJPanelLayout = new javax.swing.GroupLayout(mainGameJPanel);
        mainGameJPanel.setLayout(mainGameJPanelLayout);
        mainGameJPanelLayout.setHorizontalGroup(
            mainGameJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainGameJPanelLayout.createSequentialGroup()
                .addGroup(mainGameJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButtonjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainGameJPanelLayout.setVerticalGroup(
            mainGameJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainGameJPanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButtonjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainGameJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainGameJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goGamejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goGamejButtonActionPerformed
        monTama.goGame();
        actualiserStatus();
        VueGifjLabel.setIcon(imageAdd("kreeperGoGame", "gif"));
        this.showDialog();
        VueGifjLabel.setIcon(imageAdd("kreeper", "gif"));
    }//GEN-LAST:event_goGamejButtonActionPerformed

    private void goShowerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goShowerjButtonActionPerformed
        monTama.goShower();
        actualiserStatus();
        VueGifjLabel.setIcon(imageAdd("kreeperGoShower", "gif"));
        this.showDialog();
        VueGifjLabel.setIcon(imageAdd("kreeper", "gif"));
    }//GEN-LAST:event_goShowerjButtonActionPerformed

    private void goSleepjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goSleepjButtonActionPerformed
        monTama.goSleep();
        actualiserStatus();
        VueGifjLabel.setIcon(imageAdd("kreeperGoSleep", "gif"));
        this.showDialog();
        VueGifjLabel.setIcon(imageAdd("kreeper", "gif"));
    }//GEN-LAST:event_goSleepjButtonActionPerformed

    private void goSportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goSportjButtonActionPerformed
        monTama.goSport();
        actualiserStatus();
        VueGifjLabel.setIcon(imageAdd("kreeperGoSport", "gif"));
        this.showDialog();
        VueGifjLabel.setIcon(imageAdd("kreeper", "gif"));
    }//GEN-LAST:event_goSportjButtonActionPerformed

    private void goPoopjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goPoopjButtonActionPerformed
        monTama.goToilettes();
        actualiserStatus();
        VueGifjLabel.setIcon(imageAdd("kreeperGoPee", "gif"));
        this.showDialog();
        VueGifjLabel.setIcon(imageAdd("kreeper", "gif"));
        System.out.println("valeur " + monTama.getNom());
    }//GEN-LAST:event_goPoopjButtonActionPerformed

    private void goEatjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goEatjButtonActionPerformed
        monTama.goMiam();
        actualiserStatus();
        VueGifjLabel.setIcon(imageAdd("kreeperFeed", "gif"));
        this.showDialog();
        VueGifjLabel.setIcon(imageAdd("kreeper", "gif"));
    }//GEN-LAST:event_goEatjButtonActionPerformed

    private void testStartjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testStartjButton1ActionPerformed
       actualiserStatus();
       testStartjButton1.setVisible(false);
       backButtonjPanel.setVisible(true);
       VueGifjLabel.setIcon(imageAdd("kreeper", "gif"));
    }//GEN-LAST:event_testStartjButton1ActionPerformed

    private void suicidejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suicidejButtonActionPerformed
        monTama.goSuicide();
        actualiserStatus();
        testStartjButton1.setVisible(true);
    }//GEN-LAST:event_suicidejButtonActionPerformed

    private void nameNewjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameNewjTextField1ActionPerformed
        monTama.getNom();
    }//GEN-LAST:event_nameNewjTextField1ActionPerformed

    private void sexNewjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexNewjTextField2ActionPerformed
        sexNewjTextField2.setText(VueHomeTamagotchi.getSexjTextField().getText());
    }//GEN-LAST:event_sexNewjTextField2ActionPerformed
 
    
    
    private void actualiserStatus() {
        monTama.faucheuse();
        santeJProgressBar4.setValue(monTama.getSante() * 10);
        poidsJProgressBar2.setValue(monTama.getPoids() * 10);
        hygieneJProgressBar.setValue(monTama.getHygiene() * 10);
        faimJProgressBar3.setValue(monTama.getFaim() * 10);
        besoinJProgressBar1.setValue(monTama.getBesoin() * 10);
        humeurJProgressBar5.setValue(monTama.getHumeur() * 10);
        if (monTama.isLife() == false) {
            VueGifjLabel.setIcon(imageAdd("kreeper_Dead", "png"));
            backButtonjPanel.setVisible(false);
            testStartjButton1.setVisible(true);
        }

        OutDialjTextArea.setText(monTama.checkStatus());
    }

    public ImageIcon imageAdd(String name, String ext) {
        ImageIcon avatar = new ImageIcon(getClass().getResource("/ressources/" + name + "." + ext));
        return avatar;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueGameTamagotchi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueGameTamagotchi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueGameTamagotchi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueGameTamagotchi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        System.out.println();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueGameTamagotchi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea OutDialjTextArea;
    private javax.swing.JLabel VueGifjLabel;
    private javax.swing.JPanel backButtonjPanel;
    private javax.swing.JProgressBar besoinJProgressBar1;
    private javax.swing.JProgressBar faimJProgressBar3;
    private javax.swing.JButton goEatjButton;
    private javax.swing.JButton goGamejButton;
    private javax.swing.JButton goPoopjButton;
    private javax.swing.JButton goShowerjButton;
    private javax.swing.JButton goSleepjButton;
    private javax.swing.JButton goSportjButton;
    private javax.swing.JProgressBar humeurJProgressBar5;
    private javax.swing.JProgressBar hygieneJProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainGameJPanel;
    private javax.swing.JTextField nameNewjTextField1;
    private javax.swing.JProgressBar poidsJProgressBar2;
    private javax.swing.JProgressBar santeJProgressBar4;
    private javax.swing.JTextField sexNewjTextField2;
    private javax.swing.JButton suicidejButton;
    private javax.swing.JButton testStartjButton1;
    // End of variables declaration//GEN-END:variables
}
